apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: dev
  name: developer
rules:
- apiGroups: ["apps","extensions"]
  resources: ["deployments","configmaps", "pods", "secrets","services"]
  verbs: ["create","get","delete","list","update","edit","watch","exec","patch"]
