# Feature branch checking 
steps:
- id: Code validation
  name: gcr.io/config-management-release/nomos:stable
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    nomos vet --path=config-sync || exit 1
    echo "Configuration successfully validated"

